name: eguru_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-42.2.beta <4.0.0'

dependencies:
  appwrite: ^11.0.0
  chewie: ^1.7.1
  connectivity_plus: ^4.0.2
  dart_appwrite: ^10.0.0
  dio: ^5.3.2
  either_dart: ^1.0.0
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.2
  flutter_rating_bar: ^4.0.1
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  restart_app: ^1.2.1
  shared_preferences: ^2.2.1
  syncfusion_flutter_pdfviewer: ^22.2.12
  text_scroll: ^0.2.0
  uuid: ^3.0.7
  video_player: ^2.7.1
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  rename: ^2.1.1


flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/E-Guru.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/E-Guru.png"
    background_color: "#101c89"
    theme_color: "#101c89"
  windows:
    generate: true
    image_path: "assets/E-Guru.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/E-Guru.png"

flutter_native_splash:
  color: "#101c89"
  image: assets/E-Guru.png
  # branding: assets/branding-development.png
  color_dark: "#121212"
  image_dark: assets/E-Guru.png
  branding_dark: assets/E-Guru.png

  android_12:
    image: assets/E-Guru.png
    icon_background_color: "#101c89"
    image_dark: assets/E-Guru.png
    icon_background_color_dark: "#121212"

  web: false